// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 启动Telink OTA升级（带进度流）- 异步版本
Stream<double> startTelinkOtaWithProgress({
  required String deviceId,
  required List<int> firmwareData,
}) => RustLib.instance.api.crateApiOtaStartTelinkOtaWithProgress(
  deviceId: deviceId,
  firmwareData: firmwareData,
);

/// 启动Telink OTA升级 - 异步版本
Future<String> startTelinkOta({
  required String deviceId,
  required List<int> firmwareData,
}) => RustLib.instance.api.crateApiOtaStartTelinkOta(
  deviceId: deviceId,
  firmwareData: firmwareData,
);

/// 获取OTA状态 - 保持同步
String getOtaStatus({required String deviceId}) =>
    RustLib.instance.api.crateApiOtaGetOtaStatus(deviceId: deviceId);
