// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'cmd.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `cmp`, `eq`, `fmt`, `fmt`, `partial_cmp`

/// 任务执行事件
class BleTask {
  final BigInt taskId;
  final String deviceId;
  final String uuid;
  final OpRequest op;
  final BleTaskPriority priority;

  const BleTask({
    required this.taskId,
    required this.deviceId,
    required this.uuid,
    required this.op,
    required this.priority,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^
      deviceId.hashCode ^
      uuid.hashCode ^
      op.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BleTask &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          deviceId == other.deviceId &&
          uuid == other.uuid &&
          op == other.op &&
          priority == other.priority;
}

/// 任务优先级枚举
enum BleTaskPriority {
  low,
  normal,
  high,
}
